#!/bin/bash

# Setting environment variables
export PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
export PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-60}
export PHP_ERROR_LOG=${PHP_ERROR_LOG:-/tmp/php_errors.log}
export UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE:-20M}
export POST_MAX_SIZE=${POST_MAX_SIZE:-20M}
export AUTO_PREPEND_FILE=${AUTO_PREPEND_FILE:-${COMPOSER_HOME}/vendor/autoload.php}
export TIMEZONE=${TIMEZONE:-Europe/Rome}
export XDEBUG_IDEKEY=${XDEBUG_IDEKEY:-PHPSTORM}